//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTeknolojikMarketYonetimPaneli.Models.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TBL_GELIR
    {
        public int GELIRID { get; set; }
        public Nullable<short> GELIRSUBE { get; set; }

        [Required(ErrorMessage="Lütfen bir satýþ karý miktarý girin!")]
        [Range(0.00, 1000000.00, ErrorMessage = "0 - 1000000 TL arasýnda satýþ geliri giriniz!")]
        [DataType(DataType.Currency, ErrorMessage = "Bir para deðeri girilmelidir!")]
        public Nullable<decimal> SATISKARI { get; set; }
        public Nullable<System.DateTime> GELIRTARIHI { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual TBL_SUBE TBL_SUBE { get; set; }
    }
}
