//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTeknolojikMarketYonetimPaneli.Models.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TBL_YONETICI
    {
        public TBL_YONETICI()
        {
            this.TBL_DUYURU = new HashSet<TBL_DUYURU>();
            this.TBL_MESAJPERYON = new HashSet<TBL_MESAJPERYON>();
            this.TBL_MESAJYONPER = new HashSet<TBL_MESAJYONPER>();
        }
    
        public short YONETICIID { get; set; }

        [StringLength(30, ErrorMessage = "Maksimum ad uzunluðu 30 karakter olabilir!")]
        public string YONETICIAD { get; set; }

        [StringLength(20, ErrorMessage = "Maksimum soyad uzunluðu 20 karakter olabilir!")]
        public string YONETICISOYAD { get; set; }

        [Phone(ErrorMessage = "Böyle bir telefon numarasý olamaz!")]
        [StringLength(20, ErrorMessage = "Maksimum telefon numarasý 20 karakter olabilir!")]
        public string YONETICITELEFON { get; set; }

        [EmailAddress(ErrorMessage = "Böyle bir e-posta adresi olamaz!")]
        [StringLength(25, ErrorMessage = "Maksimum e-posta adresi 25 karakter olabilir!")]
        public string YONETICIMAIL { get; set; }
        public Nullable<short> YONETICISUBE { get; set; }

        [StringLength(11, MinimumLength = 11, ErrorMessage = "TC Numarasý 11 karakter olabilir!")]
        public string YONETICITC { get; set; }

        [Range(0.00, 100000.00, ErrorMessage = "0 - 100000 TL arasýnda maaþ ücreti giriniz!")]
        [DataType(DataType.Currency, ErrorMessage = "Bir para deðeri girilmelidir!")]
        public Nullable<decimal> YONETICIMAAS { get; set; }
        public string YONETICICINSIYET { get; set; }

        [Range(1, 100, ErrorMessage = "Yaþ 1 ile 100 arasýnda olabilir!")]
        public Nullable<byte> YONETICIYAS { get; set; }
        public Nullable<System.DateTime> YONETICIBASLANGICTARIHI { get; set; }
        public Nullable<System.DateTime> YONETICIBITISTARIHI { get; set; }

        [Required(ErrorMessage="Kullanýcý adý boþ olamaz!")]
        [StringLength(20,ErrorMessage="Kullanýcý adý maksimum 20 karakterden oluþabilir!")]
        public string KULLANICIADI { get; set; }

        [Required(ErrorMessage="Þifre boþ olamaz!")]
        [StringLength(20, ErrorMessage = "Þifre maksimum 20 karakterden oluþabilir!")]
        public string SIFRE { get; set; }
        public Nullable<bool> YONETICIDURUM { get; set; }
        public string KULLANICITIPI { get; set; }
    
        public virtual ICollection<TBL_DUYURU> TBL_DUYURU { get; set; }
        public virtual ICollection<TBL_MESAJPERYON> TBL_MESAJPERYON { get; set; }
        public virtual ICollection<TBL_MESAJYONPER> TBL_MESAJYONPER { get; set; }
        public virtual TBL_SUBE TBL_SUBE { get; set; }
    }
}
