//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTeknolojikMarketYonetimPaneli.Models.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TBL_BOLUM
    {
        public TBL_BOLUM()
        {
            this.TBL_PERSONEL = new HashSet<TBL_PERSONEL>();
        }
    
        public byte BOLUMID { get; set; }

       
        [StringLength(30,ErrorMessage="Bölüm adý maksimum 30 karakterden oluþabilir!")]
        public string BOLUMAD { get; set; }
        public Nullable<bool> BOLUMDURUM { get; set; }
    
        public virtual ICollection<TBL_PERSONEL> TBL_PERSONEL { get; set; }
    }
}
