//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTeknolojikMarketYonetimPaneli.Models.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TBL_KATEGORI
    {
        public TBL_KATEGORI()
        {
            this.TBL_URUN = new HashSet<TBL_URUN>();
        }
    
        public byte KATEGORIID { get; set; }
        
        [StringLength(30, ErrorMessage = "Maksimum 30 karaktere sahip bir kategori adý olabilir!")]
        public string KATEGORIAD { get; set; }
        public Nullable<short> KATEGORISUBE { get; set; }
        public Nullable<bool> KATEGORIDURUM { get; set; }
    
        public virtual TBL_SUBE TBL_SUBE { get; set; }
        public virtual ICollection<TBL_URUN> TBL_URUN { get; set; }
    }
}
