//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTeknolojikMarketYonetimPaneli.Models.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_ADMIN
    {
        public byte ADMINID { get; set; }

        [Required(ErrorMessage="Lütfen Kullanýcý adýný boþ býrakmayýn!")]
        [StringLength(20, ErrorMessage = "Maksimum 20 karaktere sahip kullanýcý adý olabilir!")]
        public string KULLANICIADI { get; set; }

        [Required(ErrorMessage="Lütfen þifrenizi boþ býrakmayýn!")]
        [StringLength(20, ErrorMessage = "Maksimum 20 karaktere sahip þifre olabilir!")]
        public string SIFRE { get; set; }
        public string KULLANICITIPI { get; set; }
    }
}
