//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTeknolojikMarketYonetimPaneli.Models.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TBL_URUN
    {
        public TBL_URUN()
        {
            this.TBL_SATIS = new HashSet<TBL_SATIS>();
        }
    
        public int URUNID { get; set; }

        [StringLength(50, ErrorMessage = "Maksimum 50 karaktere sahip bir ürün adý olabilir!")]
        public string URUNAD { get; set; }
        public Nullable<byte> URUNKATEGORI { get; set; }
        public Nullable<short> URUNSUBE { get; set; }

        [Required(ErrorMessage = "Stok deðeri boþ býrakýlamaz!")]
        [Range(0, 10000, ErrorMessage = "Bir ürünün stok adeti maksimum 10000 olabilir!")]
        public Nullable<short> URUNSTOK { get; set; }

        [Required(ErrorMessage = "Alýþ Fiyat deðeri boþ býrakýlamaz!")]
        [Range(0.00, 1000000.00, ErrorMessage = "0 - 1000000 TL arasýnda alýþ fiyatý giriniz!")]
        [DataType(DataType.Currency, ErrorMessage = "Bir para deðeri girilmelidir!")]
        public Nullable<decimal> URUNALISFIYAT { get; set; }

        [Required(ErrorMessage = "Satýþ Fiyat deðeri boþ býrakýlamaz!")]
        [Range(0.00, 1000000.00, ErrorMessage = "0 - 1000000 TL arasýnda satýþ fiyatý giriniz!")]
        [DataType(DataType.Currency, ErrorMessage = "Bir para deðeri girilmelidir!")]
        public Nullable<decimal> URUNSATISFIYAT { get; set; }
        public Nullable<bool> URUNDURUM { get; set; }

        [Required(ErrorMessage = "Marka adý boþ olmamalýdýr!")]
        [StringLength(20, ErrorMessage = "Maksimum 20 karakterlik bir ürün adý olmalýdýr!")]
        public string URUNMARKA { get; set; }
 
        public virtual TBL_KATEGORI TBL_KATEGORI { get; set; }
        public virtual ICollection<TBL_SATIS> TBL_SATIS { get; set; }
        public virtual TBL_SUBE TBL_SUBE { get; set; }
    }
}
