//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTeknolojikMarketYonetimPaneli.Models.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class TBL_PERSONEL
    {
        public TBL_PERSONEL()
        {
            this.TBL_MESAJPERYON = new HashSet<TBL_MESAJPERYON>();
            this.TBL_MESAJYONPER = new HashSet<TBL_MESAJYONPER>();
            this.TBL_SATIS = new HashSet<TBL_SATIS>();
        }
    
        public int PERSONELID { get; set; }

        [StringLength(30, ErrorMessage = "Maksimum ad uzunluðu 30 karakter olabilir!")]
        public string PERSONELAD { get; set; }

        [StringLength(20, ErrorMessage = "Maksimum soyad uzunluðu 20 karakter olabilir!")]
        public string PERSONELSOYAD { get; set; }
        public Nullable<short> PERSONELSUBE { get; set; }
        public Nullable<byte> PERSONELBOLUM { get; set; }

        [EmailAddress(ErrorMessage = "Böyle bir e-posta adresi olamaz!")]
        [StringLength(25, ErrorMessage = "Maksimum e-posta adresi 25 karakter olabilir!")]
        public string PERSONELMAIL { get; set; }

        [Phone(ErrorMessage = "Böyle bir telefon numarasý olamaz!")]
        [StringLength(20, ErrorMessage = "Maksimum telefon numarasý 20 karakter olabilir!")]
        public string PERSONELTELEFON { get; set; }

        [StringLength(11, MinimumLength = 11, ErrorMessage = "TC Numarasý 11 karakter olabilir!")]
        public string PERSONELTC { get; set; }

        [Range(0.00, 10000.00, ErrorMessage = "0 - 10000 TL arasýnda maaþ ücreti giriniz!")]
        [DataType(DataType.Currency, ErrorMessage = "Bir para deðeri girilmelidir!")]
        public Nullable<decimal> PERSONELMAAS { get; set; }
        public string PERSONELCINSIYET { get; set; }

        [Range(1, 100, ErrorMessage = "Yaþ 1 ile 100 arasýnda olabilir!")]
        public Nullable<byte> PERSONELYAS { get; set; }
        public Nullable<bool> PERSONELDURUM { get; set; }
        public Nullable<System.DateTime> PERSONELBASLANGICTARIHI { get; set; }
        public Nullable<System.DateTime> PERSONELBITISTARIHI { get; set; }

        //[Required(ErrorMessage = "Boþ Kullanýcý Adý olamaz!")]
        [StringLength(20, ErrorMessage = "Maksimum 20 karaktere sahip kullanýcý adý olabilir!")]
        public string KULLANICIADI { get; set; }

        //[Required(ErrorMessage = "Boþ Þifre olamaz!")]
        [StringLength(20, ErrorMessage = "Maksimum 20 karaktere sahip þifre olabilir!")]
        public string SIFRE { get; set; }

        public string KULLANICITIPI { get; set; }
    
        public virtual TBL_BOLUM TBL_BOLUM { get; set; }
        public virtual ICollection<TBL_MESAJPERYON> TBL_MESAJPERYON { get; set; }
        public virtual ICollection<TBL_MESAJYONPER> TBL_MESAJYONPER { get; set; }
        public virtual TBL_SUBE TBL_SUBE { get; set; }
        public virtual ICollection<TBL_SATIS> TBL_SATIS { get; set; }
    }
}
