//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTeknolojikMarketYonetimPaneli.Models.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TBL_SUBE
    {
        public TBL_SUBE()
        {
            this.TBL_DUYURU = new HashSet<TBL_DUYURU>();
            this.TBL_GELIR = new HashSet<TBL_GELIR>();
            this.TBL_GIDER = new HashSet<TBL_GIDER>();
            this.TBL_KATEGORI = new HashSet<TBL_KATEGORI>();
            this.TBL_MUSTERI = new HashSet<TBL_MUSTERI>();
            this.TBL_PERSONEL = new HashSet<TBL_PERSONEL>();
            this.TBL_SATIS = new HashSet<TBL_SATIS>();
            this.TBL_URUN = new HashSet<TBL_URUN>();
            this.TBL_YONETICI = new HashSet<TBL_YONETICI>();
        }
    
        public short SUBEID { get; set; }

        [StringLength(50,ErrorMessage="Þube adý maksimum 50 karakter olabilir!")]
        public string SUBEAD { get; set; }

        [Phone(ErrorMessage = "Böyle bir telefon numarasý olamaz!")]
        [StringLength(20, ErrorMessage = "Þube telefonu maksimum 20 karakter olabilir!")]
        public string SUBETELEFON { get; set; }
        public string SUBESEHIR { get; set; }

        [DataType(DataType.DateTime,ErrorMessage="Böyle bir tarih deðeri olamaz!")]
        public Nullable<System.DateTime> SUBEKURULUSTARIHI { get; set; }
        public Nullable<System.DateTime> SUBEBITISTARIHI { get; set; }
        public Nullable<bool> SUBEDURUM { get; set; }
    
        public virtual ICollection<TBL_DUYURU> TBL_DUYURU { get; set; }
        public virtual ICollection<TBL_GELIR> TBL_GELIR { get; set; }
        public virtual ICollection<TBL_GIDER> TBL_GIDER { get; set; }
        public virtual ICollection<TBL_KATEGORI> TBL_KATEGORI { get; set; }
        public virtual ICollection<TBL_MUSTERI> TBL_MUSTERI { get; set; }
        public virtual ICollection<TBL_PERSONEL> TBL_PERSONEL { get; set; }
        public virtual ICollection<TBL_SATIS> TBL_SATIS { get; set; }
        public virtual ICollection<TBL_URUN> TBL_URUN { get; set; }
        public virtual ICollection<TBL_YONETICI> TBL_YONETICI { get; set; }
    }
}
