//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTeknolojikMarketYonetimPaneli.Models.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TBL_MUSTERI
    {
        public TBL_MUSTERI()
        {
            this.TBL_SATIS = new HashSet<TBL_SATIS>();
        }
    
        public int MUSTERIID { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz!")]
        [StringLength(30, ErrorMessage = "Maksimum ad uzunluðu 30 karakter olabilir!")]
        public string MUSTERIAD { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz!")]
        [StringLength(20, ErrorMessage = "Maksimum soyad uzunluðu 20 karakter olabilir!")]
        public string MUSTERISOYAD { get; set; }
        public Nullable<short> MUSTERISUBE { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz!")]
        [Phone(ErrorMessage = "Böyle bir telefon numarasý olamaz!")]
        [StringLength(20, ErrorMessage = "Maksimum telefon numarasý 20 karakter olabilir!")]
        public string MUSTERITELEFON { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz!")]
        [EmailAddress(ErrorMessage = "Böyle bir e-posta adresi olamaz!")]
        [StringLength(25, ErrorMessage = "Maksimum e-posta adresi 25 karakter olabilir!")]
        public string MUSTERIMAIL { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz!")]
        [StringLength(11, MinimumLength = 11, ErrorMessage = "TC Numarasý 11 karakter olabilir!")]
        public string MUSTERITC { get; set; }

        public string MUSTERICINSIYET { get; set; }


        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz!")]
        [Range(1, 100, ErrorMessage = "Yaþ 1 ile 100 arasýnda olabilir!")]
        public Nullable<byte> MUSTERIYAS { get; set; }
        public Nullable<bool> MUSTERIDURUM { get; set; }

        public virtual TBL_SUBE TBL_SUBE { get; set; }
        public virtual ICollection<TBL_SATIS> TBL_SATIS { get; set; }
    }
}
