//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTeknolojikMarketYonetimPaneli.Models.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TBL_GIDER
    {
        public int GIDERID { get; set; }
        public Nullable<short> GIDERSUBE { get; set; }

        [Required(ErrorMessage = "Lütfen bir personel gideri miktarý girin!")]
        [Range(0.00, 1000000.00, ErrorMessage = "0 - 1000000 TL arasýnda personel gideri giriniz!")]
        [DataType(DataType.Currency, ErrorMessage = "Bir para deðeri girilmelidir!")]
        public Nullable<decimal> GIDERPERSONEL { get; set; }

        [Required(ErrorMessage = "Lütfen bir kira gideri miktarý girin!")]
        [Range(0.00, 1000000.00, ErrorMessage = "0 - 1000000 TL arasýnda kira gideri giriniz!")]
        [DataType(DataType.Currency, ErrorMessage = "Bir para deðeri girilmelidir!")]
        public Nullable<decimal> GIDERKIRA { get; set; }

        [Required(ErrorMessage = "Lütfen bir enerji gideri miktarý girin!")]
        [Range(0.00, 1000000.00, ErrorMessage = "0 - 1000000 TL arasýnda enerji gideri giriniz!")]
        [DataType(DataType.Currency, ErrorMessage = "Bir para deðeri girilmelidir!")]
        public Nullable<decimal> GIDERENERJI { get; set; }

        [Required(ErrorMessage = "Lütfen bir diðer giderler miktarý girin!")]
        [Range(0.00, 1000000.00, ErrorMessage = "0 - 1000000 TL arasýnda diðer giderleri giriniz!")]
        [DataType(DataType.Currency, ErrorMessage = "Bir para deðeri girilmelidir!")]
        public Nullable<decimal> GIDERDIGER { get; set; }
        public Nullable<System.DateTime> GIDERTARIHI { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual TBL_SUBE TBL_SUBE { get; set; }
    }
}
