//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTeknolojikMarketYonetimPaneli.Models.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TBL_DUYURU
    {
        public int DUYURUID { get; set; }
        public Nullable<short> YONETICI { get; set; }
        public Nullable<short> SUBE { get; set; }

        [Required(ErrorMessage="Duyuru Ýçeriði boþ olamaz!")]
        [StringLength(500,ErrorMessage="500 karakterden fazla bir duyuru içeriði olamaz!")]
        public string DUYURUICERIGI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual TBL_SUBE TBL_SUBE { get; set; }
        public virtual TBL_YONETICI TBL_YONETICI { get; set; }
    }
}
